### PR TITLE
LESS Added

### PR DESCRIPTION
**Pull request by elenatorro**
Tootik also written in LESS. I'd like to use it in a project where I'm using LESS.

### CODE REVIEW

**Comment by eliorshalev** [comment]
@elenatorro, That's awesome, Thank you.

**Comment by eliorshalev** [comment]
Elena (@elenatorro), That's awesome, Thank you.

**Comment by elenatorro** [comment]
Thank you very much! I'm actually a SASS fan, but I needed a LESS version to customize the tooltips for my project. I really liked your project because I found it very clean, simple and useful :)

**Comment by eliorshalev** [comment]
Thank you 👍 Really **happy** to get this feedback! :)

**Pull request merged**
